"""
Device model for tracking registered client devices.
"""
from sqlalchemy import Column, String, DateTime
from sqlalchemy.sql import func
from database import Base


class Device(Base):
    """Device registration model for tracking sync clients."""

    __tablename__ = "devices"

    # Device identifier (generated by client)
    id = Column(String(100), primary_key=True)

    # Device information
    device_name = Column(String(200), nullable=False)
    device_type = Column(String(50), nullable=False)  # "windows" | "android"

    # Tracking
    last_seen = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now(), nullable=False)
    created_at = Column(DateTime(timezone=True), server_default=func.now(), nullable=False)

    def __repr__(self):
        return f"<Device(id={self.id}, name='{self.device_name}', type='{self.device_type}')>"
